import { Component } from '@angular/core';
import {
  FaIconLibrary,
  FontAwesomeModule,
} from '@fortawesome/angular-fontawesome';
import { faGithub, faLinkedin } from '@fortawesome/free-brands-svg-icons';
import { faArrowUpRightFromSquare } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-projects-gallery',
  standalone: true,
  imports: [FontAwesomeModule],
  templateUrl: './projects-gallery.component.html',
  styleUrl: './projects-gallery.component.scss',
})
export class ProjectsGalleryComponent {
  projects = [
    {
      blob: true,
      blobColor: 'dark',
      blobData: 'Part time',
      imgSrc: '/assets/imgs/hemmafest.png',
      title: 'Hemmafest!',
      tags: ['App', 'Social media', 'Youth', ''],
      tagsBg: 'light',
      skills: ['App', 'Social media', 'Android', 'iOS'],
      skillsColor: 'secondary',
      body: 'App for finding/hosting house parties nearby. Top 5 apps in AppStore Dec 2024.',
      statusItems: [{ title: 'started', data: '2024' }],
      footer: 'Founder',
      githubLink: '',
      externalLink: 'https://hemmafest.catso.io',
      footerBg: '7e0059',
    },
    {
      blob: true,
      blobColor: 'blue',
      blobData: 'Paused',
      imgSrc: '/assets/imgs/movexbig.png',
      title: 'Movex',
      tags: ['Youtube', 'Content', 'Gaming', 'Creator'],
      skills: ['Photoshop', 'Sony Vegas', 'Premiere Pro', 'AI'],
      skillsColor: 'secondary',
      tagsBg: 'light',
      body: `Gaming Youtube-channel with more than 50 000 subscribers &
      4 000 000 Views`,
      statusItems: [
        { title: 'Started', data: '2015' },
        { title: 'till', data: '2021' },
      ],
      footer: 'Content Creator',
      githubLink: '',
      externalLink: 'https://youtube.com/c/IxM7MD',
      linkedInLink: '',
      footerBg: '260443',
    },
    {
      blob: true,
      blobColor: 'blue',
      blobData: 'Paused',
      imgSrc: '/assets/imgs/fortnitebox.png',
      title: 'Fortnite Box',
      tags: ['Marketplace', 'Sell', 'Buy'],
      tagsBg: 'light',
      skills: ['Full-stack', 'PHP', 'Bootstrap 4.0', 'Js'],
      skillsColor: 'secondary',
      body: 'Fortnite Box is a marketplace for selling & buying Fortnite Accounts.',
      statusItems: [
        { title: 'started', data: '2019' },
        { title: 'Till', data: '2021' },
        { title: 'revenue', data: '$16k' },
      ],
      footer: 'Founder',
      githubLink: '#',
      externalLink: '',
      footerBg: '373737',
    },
    {
      blob: true,
      blobColor: 'dark',
      blobData: 'Part time',
      imgSrc: '/assets/imgs/cattso.png',
      title: 'Catso',
      tags: ['AI', 'ML', 'E-Commerce', 'Analysis'],
      tagsBg: 'light',
      skills: ['Tensorflow', 'Js', 'Python'],
      skillsColor: 'secondary',
      body: 'Catso is an E-Commerce Data analysis Tool Powerd By AI.',
      statusItems: [{ title: 'started', data: '2022' }],
      footer: 'Solution Architect',
      githubLink: 'https://github.com/catsoio',
      externalLink: '',
      footerBg: 'd70017',
    },
    {
      blob: true,
      blobColor: 'dark',
      blobData: 'Part time',
      imgSrc: '/assets/imgs/poundlogo.png',
      title: 'Pound Inc.',
      tags: ['Training', 'Angular', 'Microservices', 'Kubernetes'],
      tagsBg: 'light',
      skills: ['NestJS', 'Angular', 'Microservices', 'Kubernetes'],
      skillsColor: 'secondary',
      body: 'Two-Sided Marketplace For Gym Coaches & Trainees.',
      statusItems: [{ title: 'started', data: '2024' }],
      footer: 'Lead Developer',
      githubLink: 'https://github.com/Pound-Inc',
      externalLink: '',
      footerBg: '1d1d1b',
    },
    {
      blob: true,
      blobColor: 'dark',
      blobData: 'Part time',
      imgSrc: '/assets/imgs/cos.jpeg',
      title: 'Celene Of Sweden',
      tags: ['Training', 'ML', 'E-Commerce', 'Analysis'],
      tagsBg: 'light',
      skills: ['E-Commerce', 'Microservices', 'ML'],
      skillsColor: 'secondary',
      body: 'E-Commerce Platform For Buying Premium Makeup Products.',
      statusItems: [{ title: 'started', data: '2024' }],
      footer: 'Founder',
      githubLink: 'https://github.com/Pound-Inc',
      externalLink: '',
      footerBg: '1c3957',
    },
  ];

  constructor(library: FaIconLibrary) {
    library.addIcons(faGithub, faLinkedin, faArrowUpRightFromSquare);
  }
}
